16Nov;     |## the plan is to add bist     \__ first I compared the version of local vs github         \__ in [script.py]             \__ at some point I removed the dependency on config_json: L416                 <       self.DRC = DRC(scan_json_file, self.technology_parameter, self.scan_dir, file_name[:file_name.find(".v")])     \__ I change the [script.py] to handle use of existing yosys script         \__ now when it comes to running netlist method             checks if tech dir exist                 if yes, check if yosys script file exists                     if yes, check user input on whether to use exsiting script             else                 create script             \-- right now there's no way to accepts user input, it should be manually set in [script.py]                 \-> def netlist(self, input_file_name, module_name, vhdl=False, use_existing_script=True): L102
    \__ adding gui for bist
        \__ copy template from
27Jul;
    |## running RISCV (AFTAB), I realized that some modules are instantiated before definition
        \__ got error:
            aftab_opt_adder_32.h:155:23: error: bit-field 'gen_halfadder' has non-integral type 'aftab_half_adder*'
            155 |     aftab_half_adder* gen_halfadder:1.ha;
            \_+ must consider ":." while renaming signals and cells
26Jul;
    |## running RISCV (AFTAB), I realized that some modules are instantiated before definition
        \__ I decided to make a seperete file for each module
    \__ defining multi-bit internal signals
        \__ splitnets doesn't work
        \__ define it as an array and forget about default namings
    \__ $_TBUF_ cells are not mapped
        \__ using iopadmap
            \__ - toutpad <celltype> <portname>:<portname>[:<portname>]
            \_- didn't work
    \__ got error " error: redefinition of (module)" caused by including a file multiple time
        \__ add #ifndef to header and footer
    \__ update the [Complex_NAgate_45.h] with a newer version that has dff
21Jul;
    I changed the yosys bin to my brew installed yosys (0.30)
        \__ I installed ghdl plugin for this yosys working on a project for [RISCV]
        \__ I put symlink to it in bin directory
        \_- got the error;
            OSError: [Errno 62] Too many levels of symbolic links:
            \_+ The reason for this error is that symbolic links with relative sources are always relative to the symlink directory, not the directory from where we created the link.
                [https://www.baeldung.com/linux/too-many-levels-of-symlinks]
            \_+ I used the absolute addressing for creating symlink
                \-> ln -s /usr/local/bin/yosys* /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/utdate/bin/darwin/bin/
        [script.py]
        \__ adding "-m ghdl" to yosys script
16Jul;
    branch:[unflatten]
    proj:[aftab_adder_subtractor]
    \++ testing systemc was successfull, compare to verilog testbench

15Jul;
    branch:[unflatten]
    proj:[aftab_adder_subtractor]
    \__ create the class sc_module_gen
    \__ make json2systemc class dependent
    \__ change the naming
        \__ replace all the symbol '.~!@#$%^&*\\\+=- in name and type with "_"
            \-> re.sub("['.~\[\]!@#$%^&*\\\+=-]", "_", string)
        \__ using regex
    \_+ everything looks fine
        \__ write a testbench for verilog
            \++ successfull
    \__ support synthesizing to a custom library
        \__ currently to custom library must use a custom script
        \__ the default library has desinged to do synthesis and mapping
            \__ mapping to a our own library (targeted fault injection)

    \__ changing the synthesis script
        \__ changed the template script
            \__ comment the flatten option
        \__ changing yosys script maker
            \__ removing the post mapping phase
    \~~ no need for post mapping file
        \__ remove it from flow
    \__ reading liberty file as blackbox adds all the cell in json file as modules
        \__ check the attributes "blackbox" of the modules before generating sc_module
    \__ write testbench for systemC

14Jul;
    |-- add support for un-flattened designs
    \__ create and checkout to a new branch; unflatten
    \__ create a new test; [aftab_adder_subtractor]
        \__ I copied that from aftab project
        \_+ syntehsize it using current flow
    |~~ make change on [site-package]
        \__ remember to update the local files
    |-- [script.h]
        \__ remove extra print
    |-- [json2hdl.h]
        \__ remove extra print
    |-- I realized that argument "config_json" is totaly useless for vhdl and verilog
        \__ remove argument "config_json"
        \__ for systemC type;
            \__ systemC only need it for
    |-- reading un-flatten design
        \__ there's only one module with attribute "top" == 1
        \__ all the other modules are entities inside top module
        \__ each of these child modules, can be treated as a separate
    \__ I check the json2hdl and json2systemc codes
        \__ only json2hdl uses the information of technology file, and that's just for checking the is_sequential_check
            to look for the clock
        \__ this means that we can treat the child module exactly as a technology cell
        \__ the difference is that child module's ports can be multi bits
    \__ there is top level class that gets the information about json file and technology_parameters
    \__ there should be a class that generates code for a single module given the json information
        \__ input of this class would be
            \-> json object of the module (cell) as top module

        \__ add includes and stuff
        \__ loop through all cells in top level json file
            \__ generate sc_module
            \__ if the module is top == 1
                \__